apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: iamnilanjan3/worker:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     app: worker   
